### ISSUE TITLE
Add license package metadata

### ISSUE THREAD

**Issue by leonright** [mattandahalfew/Levenshtein_search#20]
Hi, we have a small automated tool for verifying installed dependencies licenses (to make sure we can use them in our project) and `Levenshtein_search` does not provide license metadata ([official docs](https://packaging.python.org/specifications/core-metadata/#license)), meaning we have to utilize GitHub API to retrieve it.

Could you please specify the branch to which we should open a PR with the change (as there are currently two in this project with `develop` being fresher)?

Thank you for your time.

**Comment by mattandahalfew** [comment]
Hi, I merged the branches, so Master is the only one remaining
