### ISSUE TITLE
cibuildwheel 

### ISSUE THREAD

**Issue by fgregg** [mattandahalfew/Levenshtein_search#26]
hi @mattandahalfew ,

we’ve been using [pypa’s cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/) project to make it a lot easier to build binary wheel s for all the variations of operating systems and machine platforms.

would you like a pull request that added this?

**Comment by mattandahalfew** [comment]
Yes, that is fine. Thank you

**Comment by fgregg** [comment]
great! would you also consider changing the license back to something that's MIT compatible? unfortunately,  dedupe can't use the current versions of your library because the GPL license is not compatible with dedupe's MIT license.

I fully understand if that's something you don't want to do!

**Comment by mattandahalfew** [comment]
I don't think that's something I want to do. I'm willing to make licensing arrangements with individual parties, but I don't think I would change the license to MIT.

**Comment by fgregg** [comment]
totally understand! thanks for considering it and your great work!

**Comment by fgregg** [comment]
as dedupe can
