### ISSUE TITLE
Version 1.4.5 is no more on PyPi. Is it possible to re-upload it? 

### ISSUE THREAD

**Issue by fsal** [mattandahalfew/Levenshtein_search#29]
Version 1.4.5 of Levensthein_search is not listed anymore on PyPi. <img width="715" alt="image" src="https://user-images.githubusercontent.com/9203508/212566830-a10cfde4-85ff-4cc3-a585-c586096dce91.png">

Since there are other packages that explicitly require this version, such as https://github.com/dedupeio/dedupe,  is it possible to reupload it?

**Comment by mattandahalfew** [comment]
I have encountered [this issue](https://stackoverflow.com/questions/67849826/python-pypi-i-cannot-upload-my-module-cause-the-filename-has-already-been-used), to which there is no solution. I was forced to change the version number. If you can think of any solution, let me know.
