### ISSUE TITLE
manylinux builds

### ISSUE THREAD

**Issue by fgregg** [mattandahalfew/Levenshtein_search#8]
Hi @mattandahalfew,

For dedupe, I'd like to have all the dependencies have manylinux1 wheels available. Would you be interested in a PR for this for Levenshtein_search

Here's an example of how I've been using Travis to build manylinux wheels: 

- https://github.com/datamade/doublemetaphone/blob/master/.travis.yml#L25-L48
- https://github.com/datamade/doublemetaphone/blob/master/.manylinux-install.sh
- https://pypi.python.org/pypi/DoubleMetaphone

**Comment by mattandahalfew** [comment]
Yes, I would
